language: objective-c

matrix:
 include:
  - os: linux
    dist: trusty
    addons:
     apt:
      packages:
       - libgit2
       - clang
       - libicu-dev
  - os: osx
    osx_image: xcode8
    sudo: false
    xcode_project: Xcode/Git2Swift.xcodeproj
    xcode_scheme: Git2Swift
 allow-failures:
   - linux


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libgit2; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then https://swift.org/builds/swift-3.0-release/ubuntu1510/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu15.10.tar.gz; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzf swift-3.0-RELEASE-ubuntu15.10.tar.gz; fi

script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then Xcode/cibuild; else export PATH=swift-3.0-RELEASE-ubuntu15.10/usr/bin:"${PATH}" && ./cibuild; fi
