language: objective-c

os:
 - osx
 - linux

matrix:
 include:
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode8
 allow-failures:
   - linux

sudo: false

addons:
 apt:
  packages:
   - libgit2


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libgit2; fi

script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then Xcode/cibuild; else ./cibuild; fi

xcode_project: Xcode/Git2Swift.xcodeproj
xcode_scheme: Git2Swift

